name: "parcivadControl"

main: de.parcivad.main
version: 1.0
api-version: 1.18

author: "parcivad"
description: "plugin for multiplayer survival"

permissions:
  enderchest.open:
    description: "Player is able to open Enderchest form another player"
  inventory.open:
    description: "Player is able to open Inventory form another player"
  tablist.owner:
    description: "Gives the player the owner prefix"
  tablist.mod:
    description: "Gives the player the moderator prefix"
  tablist.dev:
    description: "Gives the player the developer prefix"
  manage.lock:
    description: "Player is able to lock or unlock the server for others"
  manage.ban:
    description: "Player is able to tempban people"
  manage.unban:
    description: "Player is able to tempunban people"
  manage.commands:
    description: "Player is able to turn command on and off"
  manage.zone:
    description: "Allows the player to set new zones"
  home.noWait:
    description: "Player has not to wait 5min"
  zone.noProtection:
    description: "Player is able to modify the zone even when all friends are offline"

commands:
  tpa:
    description: "Teleport a Player to another."
  lock:
    description: "A Command to manage some Server settings."
  pos:
    aliases: "p"
    description: "A Command to save positions in minecraft"
  ec:
    description: "A Command to open your enderchest immediately"
  inv:
    description: "A Command to open another inventory"
  spawn:
    description: "Teleports Player to Spawn"
  stats:
    description: "Shows some Minecraft Statistics"
  seed:
    description: "Shows seed to special people"
  tempban:
    description: "Player is able to ban other players for a certain time"
  tempunban:
    description: "Player can unban players that are banned for a certain time"
  commands:
    description: "Commands to enable or disable other commands of the plugin"
  home:
    description: "Player can set his own home and teleport to this"
  zone:
    description: "Player can set zones where friends can set enemy and friend to build up a save zone"